development:
  adapter: sqlite3
  database: db/emails.postgresql
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/emails.postgresql
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: db/emails.postgresql
  pool: 5
  timeout: 5000
